"""empty message

Revision ID: 0879d502bdcd
Revises: 98877888eea5
Create Date: 2022-10-23 16:04:04.685801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0879d502bdcd'
down_revision = '98877888eea5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('stocked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food', 'stocked')
    # ### end Alembic commands ###
