"""empty message

Revision ID: 743cc793df39
Revises: 0879d502bdcd
Create Date: 2022-10-23 16:04:48.125217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '743cc793df39'
down_revision = '0879d502bdcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food', 'stacked')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('stacked', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
